### ISSUE TITLE
typo in docker-compose script

### ISSUE THREAD

**Issue by musicEnfanthen** [nie-ine/Scripts#3]
there is possibly a typo in docker script ` Scripts/docker-compose-deployment-Knora-Salsah-Sipi-GraphDB/docker-compose.yml` in line 30:

```
  sipi:
    image: nieine/sipi
    ports:
      - 1024:1024
    volumes:
      - ./tmp:/tmp
      - $HOME:$HOME
      - ./images:/sipi/images
      - ../Knora/webapiTemp:/tmp/webapi_tmp/
--> ../KnoSaSi-PrenuiltImages/sipiConfig:/sipi/config
```

../KnoSaSi-Pre**built**Images/sipiConfig:/sipi/config

**Comment by afa-unibas** [comment]
Thanks! @janCstoffregen resolved? Then let's close the issue.

**Comment by janCstoffregen** [comment]
Hi, I changed it, sorry, I did not see this issue. Reto tried the script a couple of days ago, it should work. Please let me know if it does not work again. Sorry for the late reply! The installation script moved by the way: https://github.com/nie-ine/Quick-Installation-Guide---Knora-Salsah-Sipi-GraphDB
